baseURL: "https://mohibulsblog.netlify.app"
languageCode: "en-us"
title: "Mohibul Hassan"
theme: "hugo-PaperMod"
paginate: 5
enableRobotsTXT: true
enableEmoji: true
buildDrafts: false
buildFuture: false
buildExpired: false
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production
  title: Mohibul Hassan
  description: "Personal website for Mohibul Hassan where I share content based on my experiences as an Software Engineer and AI enthusiast"
  images: ['profile-pic.jpg']
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  pygmentsUseClasses: true

  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  GoogleAnalyticsID: G-DCTB3KKNMK
  disableSpecial1stPost: false
  comments: false
  hidemeta: false

  assets:
    favicon: icons/favicon.ico
    favicon16x16: icons/favicon-16x16.png
    favicon32x32: icons/favicon-32x32.png
    apple_touch_icon: icons/apple-touch-icon.png
    android-chrome: icons/android-chrome-512x512.png
    disableHLJS: true
  label:
    text: Mohibul Hassan
  homeInfoParams:
    Title: "Hi there! \U0001F44B"
    Content: |
      - Welcome to my website!. This is the right place to discover more about me if you're interested. I share my thoughts, opinions, projects showcases & experiences as a software engineer.
      -
      - Besides that, you'll find content on topics like - "Software engineering", "Java (the programming language), Javascript", "Artificial Intelligence" & so on.
      -
      - And if you enjoy reading the content, consider sharing them with your friends, family & acquiantances. Or if you believe I could improve something, leave a feedback though any of my contact details.
  socialIcons:
  - name: twitter
    url: https://twitter.com/@dhrubo555
  - name: github
    url: https://github.com/dhrubo55
  - name: medium
    url: https://medium.com/
      # - name: instagram
      # url: https://www.instagram.com/jarmos.san/
  - name: linkedin
    url: https://www.linkedin.com/in/mohibulhassan
      # - name: facebook
      # url: https://www.facebook.com/
  - name: email
    url: mailto:mohibulhassan100@gmail.com
  - name: buymeacoffee
    url: https://www.buymeacoffee.com/
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: false
    linkFullImages: true
menu:
  main:
  - name: About
    identifier: about
    url: about/
    weight: 1
  - name: Blog
    identifier: blog
    url: blog/
    weight: 2
  - identifier: resume
    name: Resume
    url: https://drive.google.com/file/d/1Ifz4ThWwalEDGUi-gOlcnnSO0gIT4yaa/view?usp=drivesdk
    weight: 3
#   - identifier: projects
#     name: Projects
#     url: projects/
#     weight: 3
      # - name: Services
      # identifier: hiring
      # name: Services
      # url: services/
      #  weight: 4
  # - name: Collaborate
  #   identifier: collaborate
  #   url: collaborations/
  #   weight: 5
  # - name: Newsletter
  #   identifier: newsletter
  #   url: https://jarmos.ck.page/newsletter
  #   weight: 6
markup:
  highlight:
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # noClasses: false
    # style: "borland"
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: native
