# Build Settings
[build]
  command = "hugo version && hugo --gc --minify --enableGitInfo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.82.1"

# Post Processing Settings
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
