# Post Processing Settings

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
[build]
  publish = "public"
  command = "hugo --gc --minify"
[context.production.environment]
  HUGO_VERSION = "0.113.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

