# Build Settings
[build]
  command = "curl -L https://github.com/gohugoio/hugo/releases/download/v0.146.7/hugo_extended_0.146.7_linux-amd64.tar.gz -o /tmp/hugo.tar.gz && mkdir -p /tmp/hugo /tmp/hugo-cache && tar -xzf /tmp/hugo.tar.gz -C /tmp/hugo && /tmp/hugo/hugo version && /tmp/hugo/hugo --gc --minify --enableGitInfo --cacheDir /tmp/hugo-cache"
  publish = "public"

# Post Processing Settings
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
