name: Compile LaTeX Resume

on:
  workflow_dispatch:  # Allow manual triggers
  push:
    branches:
      - main
    paths:
      - 'content/resume.tex'  # Only trigger on resume.tex changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up LaTeX
      uses: dante-ev/latex-action@v2

    - name: Create output directory
      run: mkdir -p static/files

    - name: Compile LaTeX document
      run: |
        latexmk -pdf -output-directory=static/files content/resume.tex
        cp static/files/resume.pdf static/resume.pdf

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: resume-pdf
        path: static/resume.pdf
