name: Compile LaTeX Resume

# Add permissions at workflow level
permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'static/resume.tex'
      - '.github/workflows/latex.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended latexmk

    - name: Compile LaTeX document
      run: |
        cd static
        latexmk -pdf resume.tex
        # This will generate resume.pdf in the same directory as resume.tex

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add static/resume.pdf
        git commit -m "Update resume.pdf" || exit 0
        git push
