name: Compile LaTeX Resume

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/resume.tex'
      - '.github/workflows/latex.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended latexmk

    - name: Create directories
      run: |
        mkdir -p static/files
        mkdir -p public/files

    - name: Compile LaTeX document
      run: |
        cd content
        latexmk -pdf -output-directory=../static/files resume.tex
        cp ../static/files/resume.pdf ../static/resume.pdf
        cp ../static/files/resume.pdf ../public/resume.pdf

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume-pdf
        path: |
          static/resume.pdf
          public/resume.pdf
